version: '3'
services:
  api:
    image: ${ECR_REPOSITORY_URI}:latest
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    logging:
      driver: awslogs
      options:
        awslogs-group: fund-holdings-logs
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs

